# Change these first
owner: leoaslan2603 # Your GitHub username
repo: leoaslan2603.github.io # Your GitHub repository name

# Add your sites here
sites:
  - name: Chot.Sale
    url: https://chot.sale
  - name: App Chot.Sale
    url: https://app.chot.sale
  - name: TCP ping to Chot.Sale server
    url: 125.212.238.170

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
